apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "rafa"
  description: "Template Spring boot desc"
  annotations:
    github.com/project-slug: RafaelSalazarLopez/TemplateRepository
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: "group:acc/acc"
